apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-notificaciones
  namespace: tutorias
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-notificaciones
  template:
    metadata:
      labels:
        app: ms-notificaciones
    spec:
      containers:
        - name: ms-notificaciones
          image: ms-notificaciones:1.0
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: ms-notificaciones
  namespace: tutorias
spec:
  selector:
    app: ms-notificaciones
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
  type: ClusterIP
